name: Copy Recursion from UIT Together

on:
  workflow_dispatch:
    inputs:
      USER_GITHUB_TOKEN:
        description: "Personal access token of the action runner"
        required: true
      USERNAME:
        description: Username of the action runner
        required: true
      EMAIL:
        description: Email of the action runner
        required: true
      USER_COMMIT_MESSAGE:
        description: Commit message of the action runner
        required: true
        default: "💥 (Bai$i): Done"
      USER_ORDER:
        description: Order of user
        required: true
      MAX_RANDOM_TIME:
        description: Max random time - Nên [1; 500]
        required: true
        default: "1"
      MIN_RANDOM_TIME:
        description: Min random time - nên min 0
        required: true
        default: "0"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ inputs.USER_GITHUB_TOKEN || secrets.USER_GITHUB_TOKEN }}
  SOURCE_REPO_LINK: https://github.com/UIT-Together-2022-Team-Nobita/Recursion-CPP
  TARGET_REPO: ${{ vars.OWNER_REPO }}
  USERNAME: ${{ inputs.USERNAME }}
  EMAIL: ${{ inputs.EMAIL }}
  USER_COMMIT_MESSAGE: ${{ inputs.USER_COMMIT_MESSAGE }}
  USER_ORDER: ${{ inputs.USER_ORDER }}
  NUMBER_OF_MEMS: 5
  NUMBER_OF_PROJECTS: 191
  MAX_RANDOM_TIME: ${{ inputs.MAX_RANDOM_TIME }}
  MIN_RANDOM_TIME: ${{ inputs.MIN_RANDOM_TIME }}

permissions: write-all

jobs:
  copy:
    name: Copy Recursion from UIT Together
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ env.GITHUB_TOKEN }}

      - name: Download UIT Together's Repo
        run: git clone --depth 1 ${{ env.SOURCE_REPO_LINK }} Recursion-UIT-Together

      - name: Run script to copy
        continue-on-error: true
        run: |
          wget https://raw.githubusercontent.com/NMLT-NTTMK-K18/Utilities/main/Shell%20scripts/copyRecursionFromK17.sh
          chmod +x copyRecursionFromK17.sh
          ./copyRecursionFromK17.sh ${{ env.USERNAME}} ${{ env.EMAIL }} ${{ env.USER_COMMIT_MESSAGE }} ${{ env.USER_ORDER }} ${{ env.NUMBER_OF_MEMS }} ${{ env.NUMBER_OF_PROJECTS }} ${{ env.MAX_RANDOM_TIME }} ${{ env.MIN_RANDOM_TIME }}
          rm -f copyRecursionFromK17.sh

      - name: Push changes
        run: |
          echo "Fetch repo"
          git fetch
          if ! git status -uno | grep "Your branch is ahead of" >/dev/null 2>&1; then
            echo "Working tree is behind upstream so pull, add, commit and push"
            git config pull.rebase true
            git pull origin main
            git commit -am "Merge from upstream"
            git push origin main
          else
            echo "Push changes"
            git push origin main
          fi
